site_name: Assumed Payments
site_description: Assumed payments extension to generate and process recurring contributions.
site_author: ortiz
repo_url: https://github.com/systopia/de.systopia.cashautopay

theme:
  name: material

nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - Configuration: configuration.md
  - Usage: usage.md
  - API (CLI / APIv4): api.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
